In [1]:
import numpy as np
import pandas as pd

In [2]:
sales= pd.read_csv("sales.csv")
purchases = pd.read_csv("purchases.csv")
purchase_prices = pd.read_csv("purchase_prices.csv")
vendor_invoice = pd.read_csv("vendor_invoice.csv")
begin_inventory = pd.read_csv("begin_inventory.csv")
end_inventory = pd.read_csv("end_inventory.csv")

In [3]:
sales.head()

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [4]:
 sales.shape

(12825363, 14)

In [5]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12825363 entries, 0 to 12825362
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   SalesQuantity   int64
 6   SalesDollars    float64
 7   SalesPrice      float64
 8   SalesDate       object
 9   Volume          float64
 10  Classification  int64
 11  ExciseTax       float64
 12  VendorNo        int64
 13  VendorName      object
dtypes: float64(4), int64(5), object(5)
memory usage: 1.3+ GB

In [19]:
purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372474 entries, 0 to 2372473
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   VendorNumber    int64
 6   VendorName      object
 7   PONumber        int64
 8   PODate          object
 9   ReceivingDate   object
 10  InvoiceDate     object
 11  PayDate         object
 12  PurchasePrice   float64
 13  Quantity        int64
 14  Dollars         float64
 15  Classification  int64
dtypes: float64(2), int64(6), object(8)
memory usage: 289.6+ MB

In [20]:
purchase_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12261 entries, 0 to 12260
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           12261 non-null  int64
 1   Description     12260 non-null  object
 2   Price           12261 non-null  float64
 3   Size            12256 non-null  object
 4   Volume          12256 non-null  object
 5   Classification  12261 non-null  int64
 6   PurchasePrice   12261 non-null  float64
 7   VendorNumber    12261 non-null  int64
 8   VendorName      12261 non-null  object
dtypes: float64(2), int64(3), object(4)
memory usage: 862.2+ KB

In [25]:
vendor_invoice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5543 entries, 0 to 5542
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   VendorNumber  5543 non-null   int64
 1   VendorName    5543 non-null   object
 2   InvoiceDate   5543 non-null   object
 3   PONumber      5543 non-null   int64
 4   PODate        5543 non-null   object
 5   PayDate       5543 non-null   object
 6   Quantity      5543 non-null   int64
 7   Dollars       5543 non-null   float64
 8   Freight       5543 non-null   float64
 9   Approval      374 non-null    object
dtypes: float64(2), int64(3), object(5)
memory usage: 433.2+ KB

In [26]:
begin_inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206529 entries, 0 to 206528
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InventoryId  206529 non-null  object
 1   Store        206529 non-null  int64
 2   City         206529 non-null  object
 3   Brand        206529 non-null  int64
 4   Description  206529 non-null  object
 5   Size         206529 non-null  object
 6   onHand       206529 non-null  int64
 7   Price        206529 non-null  float64
 8   startDate    206529 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 14.2+ MB

In [24]:
end_inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224489 entries, 0 to 224488
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InventoryId  224489 non-null  object
 1   Store        224489 non-null  int64
 2   City         223205 non-null  object
 3   Brand        224489 non-null  int64
 4   Description  224489 non-null  object
 5   Size         224489 non-null  object
 6   onHand       224489 non-null  int64
 7   Price        224489 non-null  float64
 8   endDate      224489 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 15.4+ MB

In [8]:
sales.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              0
SalesQuantity     0
SalesDollars      0
SalesPrice        0
SalesDate         0
Volume            0
Classification    0
ExciseTax         0
VendorNo          0
VendorName        0
dtype: int64

In [10]:
purchases.isnull().sum()

InventoryId       0
Store             0
Brand             0
Description       0
Size              3
VendorNumber      0
VendorName        0
PONumber          0
PODate            0
ReceivingDate     0
InvoiceDate       0
PayDate           0
PurchasePrice     0
Quantity          0
Dollars           0
Classification    0
dtype: int64

In [11]:
purchase_prices.isnull().sum()

Brand             0
Description       1
Price             0
Size              1
Volume            1
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [12]:
vendor_invoice.isnull().sum()

VendorNumber       0
VendorName         0
InvoiceDate        0
PONumber           0
PODate             0
PayDate            0
Quantity           0
Dollars            0
Freight            0
Approval        5169
dtype: int64

In [13]:
begin_inventory.isnull().sum()

InventoryId    0
Store          0
City           0
Brand          0
Description    0
Size           0
onHand         0
Price          0
startDate      0
dtype: int64

In [14]:
end_inventory.isnull().sum()

InventoryId       0
Store             0
City           1284
Brand             0
Description       0
Size              0
onHand            0
Price             0
endDate           0
dtype: int64

In [33]:
purchase_prices.replace("Unknown", np.nan, inplace=True)

In [34]:
purchase_prices.isnull().sum()

Brand             0
Description       1
Price             0
Size              5
Volume            5
Classification    0
PurchasePrice     0
VendorNumber      0
VendorName        0
dtype: int64

In [35]:
purchase_prices["Volume"].unique()

array(['750', '1000', '1750', '50', '375', '100', '200', '300', nan,
       '250', '1500', '3000', '5000', '4000', '187', '150', '500', '720',
       '650', '330', '18000', '180', '6000', '20', '20000', '162.5',
       '400', '1100', '600', '19500', '560', '3750', '9000'], dtype=object)

In [37]:
sales["SalesDate"] = pd.to_datetime(sales["SalesDate"])

purchases["PODate"] = pd.to_datetime(purchases["PODate"])
purchases["ReceivingDate"] = pd.to_datetime(purchases["ReceivingDate"])
purchases["InvoiceDate"] = pd.to_datetime(purchases["InvoiceDate"])
purchases["PayDate"] = pd.to_datetime(purchases["PayDate"])

vendor_invoice["InvoiceDate"] = pd.to_datetime(vendor_invoice["InvoiceDate"])
vendor_invoice["PODate"] = pd.to_datetime(vendor_invoice["PODate"])
vendor_invoice["PayDate"] = pd.to_datetime(vendor_invoice["PayDate"])

begin_inventory["startDate"] = pd.to_datetime(begin_inventory["startDate"])

end_inventory["endDate"] = pd.to_datetime(end_inventory["endDate"])

In [38]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12825363 entries, 0 to 12825362
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   InventoryId     object
 1   Store           int64
 2   Brand           int64
 3   Description     object
 4   Size            object
 5   SalesQuantity   int64
 6   SalesDollars    float64
 7   SalesPrice      float64
 8   SalesDate       datetime64[ns]
 9   Volume          float64
 10  Classification  int64
 11  ExciseTax       float64
 12  VendorNo        int64
 13  VendorName      object
dtypes: datetime64[ns](1), float64(4), int64(5), object(4)
memory usage: 1.3+ GB

In [39]:
purchase_prices[
    purchase_prices.isnull().any(axis=1)
]

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
542,2993,Angostura Bitters,7.49,NaN,NaN,1,5.39,5895,"Mizkan Americas, Inc."
5921,9908,Tito's Copper Mug 2 Pack,21.01,NaN,NaN,1,16.15,4425,MARTIGNETTI COMPANIES
7915,4202,NaN,0.00,NaN,NaN,1,11.19,480,BACARDI USA INC
8795,8992,Group 92,1.99,NaN,NaN,1,1.43,1703,ALISA CARR BEVERAGES
10009,90590,Overture Champagne 2Glass Pk,19.95,NaN,NaN,2,13.12,4425,MARTIGNETTI COMPANIES

In [40]:
purchases[
    purchases["Size"].isnull()
]

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
1109668,34_PITMERDEN_3121,34,3121,Pinnacle Rainbow Sherbet,NaN,12546,JIM BEAM BRANDS COMPANY,10938,2024-06-27,2024-07-04,2024-07-13,2024-08-16,6.93,7,48.51,1
1112426,34_PITMERDEN_5678,34,5678,Skinnygirl Pina Colada,NaN,12546,JIM BEAM BRANDS COMPANY,10938,2024-06-27,2024-07-09,2024-07-13,2024-08-16,6.93,6,41.58,1
1116302,39_EASTHALLOW_15365,39,15365,Alabaster 07 Tinta de Toro,NaN,9552,M S WALKER INC,10972,2024-06-29,2024-07-07,2024-07-13,2024-08-21,91.83,1,91.83,2

In [41]:
end_inventory[
    end_inventory["City"].isnull()
].head()

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
113895,46__58,46,NaN,58,Gekkeikan Black & Gold Sake,750mL,0,12.99,2024-12-31
113896,46__62,46,NaN,62,Herradura Silver Tequila,750mL,0,36.99,2024-12-31
113897,46__63,46,NaN,63,Herradura Reposado Tequila,750mL,0,38.99,2024-12-31
113898,46__77,46,NaN,77,Three Olives Espresso Vodka,750mL,0,14.99,2024-12-31
113899,46__106,46,NaN,106,Mr Boston Peach Schnapps,Liter,0,4.49,2024-12-31

In [42]:
purchases.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

In [43]:
purchase_prices.head()

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

In [45]:
vendor_invoice.head()

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,NaN
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,NaN
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,NaN
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,NaN
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,NaN

In [46]:
sales.head()

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-- purchase_summary gives vendor wise purchse history --

In [49]:
purchase_summary = purchases.groupby(
    ["VendorNumber", "VendorName"]
).agg({
    "Quantity": "sum",
    "PurchasePrice": "mean"
}).reset_index()

purchase_summary.head()

,VendorNumber,VendorName,Quantity,PurchasePrice
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",328,18.583077
1,54,AAPER ALCOHOL & CHEMICAL CO,1,105.070000
2,60,ADAMBA IMPORTS INTL INC,4732,16.230879
3,105,ALTAMAR BRANDS LLC,332,35.272807
4,200,AMERICAN SPIRITS EXCHANGE,132,9.180000

In [50]:
sales_summary = sales.groupby(
    ["VendorNo", "VendorName"]
).agg({
    "SalesQuantity": "sum",
    "SalesDollars": "sum",
    "SalesPrice": "mean"
}).reset_index()

sales_summary.head()

,VendorNo,VendorName,SalesQuantity,SalesDollars,SalesPrice
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",42,1265.58,28.682308
1,60,ADAMBA IMPORTS INTL INC,3978,67576.22,16.993223
2,105,ALTAMAR BRANDS LLC,325,15748.75,48.873895
3,200,AMERICAN SPIRITS EXCHANGE,103,1719.97,14.490000
4,287,APPOLO VINEYARDS LLC,108,1616.92,15.025714

In [51]:
vendor_summary = purchase_summary.merge(
    sales_summary,
    left_on="VendorNumber",
    right_on="VendorNo",
    how="left"
)

vendor_summary.head()

,VendorNumber,VendorName_x,Quantity,PurchasePrice,VendorNo,VendorName_y,SalesQuantity,SalesDollars,SalesPrice
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",328,18.583077,2.0,"IRA GOLDMAN AND WILLIAMS, LLP",42.0,1265.58,28.682308
1,54,AAPER ALCOHOL & CHEMICAL CO,1,105.070000,NaN,NaN,NaN,NaN,NaN
2,60,ADAMBA IMPORTS INTL INC,4732,16.230879,60.0,ADAMBA IMPORTS INTL INC,3978.0,67576.22,16.993223
3,105,ALTAMAR BRANDS LLC,332,35.272807,105.0,ALTAMAR BRANDS LLC,325.0,15748.75,48.873895
4,200,AMERICAN SPIRITS EXCHANGE,132,9.180000,200.0,AMERICAN SPIRITS EXCHANGE,103.0,1719.97,14.490000

In [52]:
invoice_summary = vendor_invoice.groupby(
    ["VendorNumber", "VendorName"]
).agg({
    "Freight": "sum",
    "Dollars": "sum"
}).reset_index()

invoice_summary.head()

   VendorNumber                               VendorName  Freight   Dollars
0             2  IRA GOLDMAN AND WILLIAMS, LLP              27.08   5630.88
1            54              AAPER ALCOHOL & CHEMICAL CO     0.48    105.07
2            60              ADAMBA IMPORTS INTL INC       367.52  76770.25
3           105              ALTAMAR BRANDS LLC             62.39  11706.20
4           200              AMERICAN SPIRITS EXCHANGE       6.19   1205.16

In [53]:
vendor_summary = vendor_summary.merge(
    invoice_summary,
    on="VendorNumber",
    how="left"
)

vendor_summary.head()

,VendorNumber,VendorName_x,Quantity,PurchasePrice,VendorNo,VendorName_y,SalesQuantity,SalesDollars,SalesPrice,VendorName,Freight,Dollars
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",328,18.583077,2.0,"IRA GOLDMAN AND WILLIAMS, LLP",42.0,1265.58,28.682308,"IRA GOLDMAN AND WILLIAMS, LLP",27.08,5630.88
1,54,AAPER ALCOHOL & CHEMICAL CO,1,105.070000,NaN,NaN,NaN,NaN,NaN,AAPER ALCOHOL & CHEMICAL CO,0.48,105.07
2,60,ADAMBA IMPORTS INTL INC,4732,16.230879,60.0,ADAMBA IMPORTS INTL INC,3978.0,67576.22,16.993223,ADAMBA IMPORTS INTL INC,367.52,76770.25
3,105,ALTAMAR BRANDS LLC,332,35.272807,105.0,ALTAMAR BRANDS LLC,325.0,15748.75,48.873895,ALTAMAR BRANDS LLC,62.39,11706.20
4,200,AMERICAN SPIRITS EXCHANGE,132,9.180000,200.0,AMERICAN SPIRITS EXCHANGE,103.0,1719.97,14.490000,AMERICAN SPIRITS EXCHANGE,6.19,1205.16

In [55]:
vendor_summary["EstimatedProfit"] = (
    vendor_summary["SalesDollars"]
    - vendor_summary["Dollars"]
    - vendor_summary["Freight"]
)

vendor_summary.head()

,VendorNumber,VendorName_x,Quantity,PurchasePrice,VendorNo,VendorName_y,SalesQuantity,SalesDollars,SalesPrice,VendorName,Freight,Dollars,EstimatedProfit
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",328,18.583077,2.0,"IRA GOLDMAN AND WILLIAMS, LLP",42.0,1265.58,28.682308,"IRA GOLDMAN AND WILLIAMS, LLP",27.08,5630.88,-4392.38
1,54,AAPER ALCOHOL & CHEMICAL CO,1,105.070000,NaN,NaN,NaN,NaN,NaN,AAPER ALCOHOL & CHEMICAL CO,0.48,105.07,NaN
2,60,ADAMBA IMPORTS INTL INC,4732,16.230879,60.0,ADAMBA IMPORTS INTL INC,3978.0,67576.22,16.993223,ADAMBA IMPORTS INTL INC,367.52,76770.25,-9561.55
3,105,ALTAMAR BRANDS LLC,332,35.272807,105.0,ALTAMAR BRANDS LLC,325.0,15748.75,48.873895,ALTAMAR BRANDS LLC,62.39,11706.20,3980.16
4,200,AMERICAN SPIRITS EXCHANGE,132,9.180000,200.0,AMERICAN SPIRITS EXCHANGE,103.0,1719.97,14.490000,AMERICAN SPIRITS EXCHANGE,6.19,1205.16,508.62

In [56]:
vendor_summary[[
    "VendorName",
    "SalesDollars",
    "Dollars",
    "Freight",
    "EstimatedProfit"
]].head(10)

,VendorName,SalesDollars,Dollars,Freight,EstimatedProfit
0,"IRA GOLDMAN AND WILLIAMS, LLP",1265.58,5630.88,27.08,-4392.38
1,AAPER ALCOHOL & CHEMICAL CO,NaN,105.07,0.48,NaN
2,ADAMBA IMPORTS INTL INC,67576.22,76770.25,367.52,-9561.55
3,ALTAMAR BRANDS LLC,15748.75,11706.20,62.39,3980.16
4,AMERICAN SPIRITS EXCHANGE,1719.97,1205.16,6.19,508.62
5,APPOLO VINEYARDS LLC,1616.92,2399.70,12.28,-795.06
6,ATLANTIC IMPORTING COMPANY,59272.75,41116.32,211.74,17944.69
7,BACARDI USA INC,25014556.89,17624378.72,89286.27,7300891.90
8,BANFI PRODUCTS CORP,2646325.62,1628866.68,8510.41,1008948.53
9,STATE WINE & SPIRITS,2299075.40,1529682.04,8014.98,761378.38

In [57]:
final_vendor_analysis = vendor_summary[[
    "VendorNumber",
    "VendorName",
    "SalesQuantity",
    "SalesDollars",
    "Quantity",
    "Dollars",
    "Freight",
    "EstimatedProfit"
]]

final_vendor_analysis.head()

,VendorNumber,VendorName,SalesQuantity,SalesDollars,Quantity,Dollars,Freight,EstimatedProfit
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",42.0,1265.58,328,5630.88,27.08,-4392.38
1,54,AAPER ALCOHOL & CHEMICAL CO,NaN,NaN,1,105.07,0.48,NaN
2,60,ADAMBA IMPORTS INTL INC,3978.0,67576.22,4732,76770.25,367.52,-9561.55
3,105,ALTAMAR BRANDS LLC,325.0,15748.75,332,11706.20,62.39,3980.16
4,200,AMERICAN SPIRITS EXCHANGE,103.0,1719.97,132,1205.16,6.19,508.62

In [58]:
final_vendor_analysis.to_csv(
    "final_vendor_analysis.csv",
    index=False
)

In [4]:
brand_summary = sales.groupby("Description").agg({
    "SalesDollars": "sum"
}).reset_index()

brand_summary.head()

                    Description  SalesDollars
0                        (RI) 1      21519.09
1       .nparalleled Svgn Blanc       1094.63
2           10 Span Cab Svgn CC       2703.89
3              10 Span Chard CC       3325.56
4  10 Span Pnt Gris Monterey Cy       2082.22

In [5]:
brand_summary.to_csv(
    "brand_summary.csv",
    index=False
)

In [3]:
brand_summary = sales.groupby("Description").agg({
    "SalesDollars": "sum",
    "SalesPrice": "mean"
}).reset_index()

brand_summary["ProfitMargin"] = (
    brand_summary["SalesPrice"] / 
    brand_summary["SalesPrice"].max()
) * 100

brand_summary.head()

                    Description  SalesDollars  SalesPrice  ProfitMargin
0                        (RI) 1      21519.09   36.396015      0.627519
1       .nparalleled Svgn Blanc       1094.63    7.990000      0.137759
2           10 Span Cab Svgn CC       2703.89    7.490000      0.129138
3              10 Span Chard CC       3325.56    7.490000      0.129138
4  10 Span Pnt Gris Monterey Cy       2082.22    7.490000      0.129138

In [4]:
brand_summary.to_csv(
    "brand_summary.csv",
    index=False
)